authentication/urls.py
from django.conf.urls import  url
from django.utils.translation import ugettext as _
from . import views
from django.contrib.auth import views as vi

from authentication.forms import SetPasswordFormEdited, AuthenticationFormEdited


urlpatterns = [
                        url(r'^login/$', vi.login, {
                            'template_name': 'authentication/login.html',
                            'authentication_form': AuthenticationFormEdited,
                            'extra_context': {
                                'page': {
                                    'title': _('Log in'),
                                },
                            }
                        }, name='login'),
                        url(r'^logout/$', vi.logout, {
                            'next_page': '/',
                        }, name='logout'),
                       

                        ]

main/urls.py
from django.conf.urls import url
from django.contrib import admin
from main import views

urlpatterns = [
    url(r'^$',views.home2,name='home'),
    url(r'^contact/$',views.contact,name='contact'),
    url(r'^service/detail/(?P<service_pk>.+)/$',views.service_detail,name='service_detail'),
    url(r'^post/detail/(?P<post_pk>.+)/$',views.post_detail,name='post_detail'),
    url(r'^getservices/$',views.get_services,name='get_services'),
    url(r'^getcontries/$',views.get_contries,name='get_contries'),
    url(r'^getknow/$',views.get_know,name='get_know'),
    url(r'^getstates/(?P<country_pk>.+)/$',views.get_states,name='get_states'),
]

panel/urls.py
from django.conf.urls import url
from panel import views

urlpatterns = [
    url(r'^configuration/$',views.configuration,name='configuration'),
    url(r'^configuration/edit/stats/$',views.configuration_stats,name='configuration_stats'),
    url(r'^configuration/edit/rss/$',views.configuration_rss,name='configuration_rss'),
    url(r'^slider/list/$',views.slider_list,name='slider_list'),
    url(r'^slider/new/$',views.slider_new,name='slider_new'),
    url(r'^slider/edit/(?P<slider_pk>.+)/$',views.slider_edit,name='slider_edit'),
    url(r'^slider/delete/(?P<slider_pk>.+)/$',views.slider_delete,name='slider_delete'),
	url(r'^service/list/$',views.service_list,name='service_list'),
    url(r'^service/new/$',views.service_new,name='service_new'),
    url(r'^service/edit/(?P<service_pk>.+)/$',views.service_edit,name='service_edit'),
    url(r'^service/delete/(?P<service_pk>.+)/$',views.service_delete,name='service_delete'),
    url(r'^service/detail/(?P<service_pk>.+)/$',views.service_detail,name='service_detail'),
	url(r'^pilar/list/$',views.pilar_list,name='pilar_list'),
    url(r'^pilar/new/$',views.pilar_new,name='pilar_new'),
    url(r'^pilar/edit/(?P<pilar_pk>.+)/$',views.pilar_edit,name='pilar_edit'),
    url(r'^pilar/delete/(?P<pilar_pk>.+)/$',views.pilar_delete,name='pilar_delete'),
    url(r'^testimonio/list/$',views.testimony_list,name='testimony_list'),
    url(r'^testimonio/new/$',views.testimony_new,name='testimony_new'),
    url(r'^testimonio/edit/(?P<testimony_pk>.+)/$',views.testimony_edit,name='testimony_edit'),
    url(r'^testimonio/delete/(?P<testimony_pk>.+)/$',views.testimony_delete,name='testimony_delete'),
    url(r'^$',views.team_list,name='team_list'),
    url(r'^equipo/new/$',views.team_new,name='team_new'),
    url(r'^equipo/edit/(?P<team_pk>.+)/$',views.team_edit,name='team_edit'),
    url(r'^equipo/delete/(?P<team_pk>.+)/$',views.team_delete,name='team_delete'),
    url(r'^option/list/$',views.option_list,name='option_list'),
    url(r'^option/new/$',views.option_new,name='option_new'),
    url(r'^option/edit/(?P<option_pk>.+)/$',views.option_edit,name='option_edit'),
    url(r'^option/delete/(?P<option_pk>.+)/$',views.option_delete,name='option_delete'),
    url(r'^post/list/$',views.post_list,name='post_list'),
    url(r'^post/new/$',views.post_new,name='post_new'),
    url(r'^post/edit/(?P<post_pk>.+)/$',views.post_edit,name='post_edit'),
    url(r'^post/delete/(?P<post_pk>.+)/$',views.post_delete,name='post_delete'),
    url(r'^comment/list/(?P<post_pk>.+)/$',views.comment_list,name='comment_list'),
    url(r'^comment/new/(?P<post_pk>.+)/$',views.comment_new,name='comment_new'),
    url(r'^comment/edit/(?P<comment_pk>.+)/$',views.comment_edit,name='comment_edit'),
    url(r'^comment/delete/(?P<comment_pk>.+)/$',views.comment_delete,name='comment_delete'),
    url(r'^comment/child/list/(?P<comment_pk>.+)/$',views.comment_child_list,name='comment_child_list'),
    url(r'^comment/child/(?P<comment_pk>.+)/$',views.comment_child,name='comment_child'),
    url(r'^objetvie/new/(?P<course_pk>.+)/$',views.objetive_new,name='objetive_new'),
    url(r'^objetvie/edit/(?P<course_pk>.+)/(?P<objetive_pk>.+)/$',views.objetive_edit,name='objetive_edit'),
    url(r'^objetvie/delete/(?P<course_pk>.+)/(?P<objetive_pk>.+)/$',views.objetive_delete,name='objetive_delete'),
    #Atentiton hours
    url(r'^atention/new/$',views.atention_new,name='atention_new'),
    url(r'^atention/edit/(?P<atention_pk>.+)/$',views.atention_edit,name='atention_edit'),
    url(r'^atention/delete/(?P<atention_pk>.+)/$',views.atention_delete,name='atention_delete'),
    #Contact Detail
    url(r'^contact/new/$',views.contact_new,name='contact_new'),
    url(r'^contact/edit/(?P<contact_pk>.+)/$',views.contact_edit,name='contact_edit'),
    url(r'^contact/delete/(?P<contact_pk>.+)/$',views.contact_delete,name='contact_delete'),
    #Location Detail
    url(r'^location/new/$',views.location_new,name='location_new'),
    url(r'^location/edit/(?P<location_pk>.+)/$',views.location_edit,name='location_edit'),
    url(r'^location/delete/(?P<location_pk>.+)/$',views.location_delete,name='location_delete'),
]

src/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('main.urls',namespace='main')),
    url(r'^auth/', include('authentication.urls',namespace='authentication')),
    url(r'^panel/', include('panel.urls',namespace='panel')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

panel/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.core.urlresolvers import reverse

from django.contrib.auth.decorators import login_required
from panel.forms import *
from panel.models import *
# Create your views here.
@login_required
def home(request):
	return render(request,'panel/home.html',locals())
@login_required
def slider_list(request):
	sliders=Slider.objects.all()
	return render(request,'panel/slider/list.html',locals())
@login_required
def slider_new(request):
	title='Crear Slider'
	if request.POST:
		form=SliderForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:slider_list'))
		else:
			message="Revisa la informacion"
	else:
		form=SliderForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def slider_edit(request,slider_pk):
	slider=Slider.objects.get(pk=slider_pk)
	title='Editar Slider {0} - {1}'.format(slider.pk,slider.title)
	if request.POST:
		form=SliderForm(request.POST,request.FILES,instance=slider)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:slider_list'))
		else:
			message='Revisa la informacion'
	else:
		form=SliderForm(instance=slider)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def slider_delete(request,slider_pk):
	slider=Slider.objects.get(pk=slider_pk)
	slider.delete()
	return redirect(reverse('panel:slider_list'))
@login_required
def service_list(request):
	services=Service.objects.all()
	return render(request,'panel/service/list.html',locals())
@login_required
def service_new(request):
	title='Crear Servicio'
	if request.POST:
		form=ServiceForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_list'))
		else:
			message="Revisa la informacion"
	else:
		form=ServiceForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def service_edit(request,service_pk):
	service=Service.objects.get(pk=service_pk)
	title='Editar Servicio {0} - {1}'.format(service.pk,service.title)
	if request.POST:
		form=ServiceForm(request.POST,request.FILES,instance=service)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_list'))
		else:
			message='Revisa la informacion'
	else:
		form=ServiceForm(instance=service)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def service_delete(request,service_pk):
	service=Service.objects.get(pk=service_pk)
	service.delete()
	return redirect(reverse('panel:service_list'))
@login_required
def service_detail(request,service_pk):
	service=get_object_or_404(Service,pk=service_pk)
	title='Detalle Servicio {0}'.format(service.title)
	try:
		course=Course.objects.get(service__pk=service_pk)
	except Course.DoesNotExist:
		course=None
	if request.POST:
		if course:
			form=CourseForm(request.POST,request.FILES,instance=course)
		else:
			form=CourseForm(request.POST,request.FILES)
		if form.is_valid():
			if course:
				form.save()
			else:
				course=form.save(commit=False)
				course.service=service
				course.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':service.pk}))
		else:
			message='Revisa la informacion'
	else:
		if course:
			form=CourseForm(instance=course)
		else:
			form=CourseForm()
	if course:
		objetives=CourseObjetive.objects.filter(course=course)
		show_table=True
	else:
		objetives=None
		show_table=False
	return render(request,'panel/service/service_detail.html',locals())
@login_required
def pilar_list(request):
	pilars=Pilar.objects.all()
	return render(request,'panel/pilar/list.html',locals())
@login_required
def pilar_new(request):
	title='Crear Pilar de la empresa'
	if request.POST:
		form=PilarForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:pilar_list'))
		else:
			message="Revisa la informacion"
	else:
		form=PilarForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def pilar_edit(request,pilar_pk):
	pilar=Pilar.objects.get(pk=pilar_pk)
	title='Editar Pilar de la empresa {0} '.format(pilar.pk)
	if request.POST:
		form=PilarForm(request.POST,request.FILES,instance=pilar)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:pilar_list'))
		else:
			message='Revisa la informacion'
	else:
		form=PilarForm(instance=pilar)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def pilar_delete(request,pilar_pk):
	pilar=Pilar.objects.get(pk=pilar_pk)
	pilar.delete()
	return redirect(reverse('panel:pilar_list'))
@login_required
def option_list(request):
	options=OptionChoise.objects.all().order_by('created_at')
	return render(request,'panel/option/list.html',locals())
@login_required
def option_new(request):
	title='Crear Opcion para elegirnos'
	if request.POST:
		form=OptionForm(request.POST,request.FILES)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:option_list'))
		else:
			message="Revisa la informacion"
	else:
		form=OptionForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def option_edit(request,option_pk):
	option=OptionChoise.objects.get(pk=option_pk)
	title='Editar Opcion para elegirnos{0} -{1} '.format(option.pk,option.title)
	if request.POST:
		form=OptionForm(request.POST,request.FILES,instance=option)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:option_list'))
		else:
			message='Revisa la informacion'
	else:
		form=OptionForm(instance=option)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def option_delete(request,option_pk):
	option=OptionChoise.objects.get(pk=option_pk)
	option.delete()
	return redirect(reverse('panel:option_list'))


@login_required
def objetive_new(request,course_pk):
	course=Course.objects.get(pk=course_pk)
	title='Crear Objetivo'
	if request.POST:
		form=CourseObjetiveForm(request.POST,request.FILES)
		if form.is_valid():
			objetive=form.save(commit=False)
			objetive.course=course
			objetive.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
		else:
			message="Revisa la informacion"
	else:
		form=CourseObjetiveForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def objetive_edit(request,course_pk,objetive_pk):
	objetive=CourseObjetive.objects.get(pk=objetive_pk)
	course=Course.objects.get(pk=course_pk)

	title='Editar Objetivo'
	if request.POST:
		form=CourseObjetiveForm(request.POST,request.FILES,instance=objetive)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
		else:
			message='Revisa la informacion'
	else:
		form=CourseObjetiveForm(instance=objetive)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def objetive_delete(request,course_pk,objetive_pk):
	course=Course.objects.get(pk=course_pk)	
	objetive=CourseObjetive.objects.get(pk=objetive_pk)
	objetive.delete()
	return redirect(reverse('panel:service_detail',kwargs={'service_pk':course.service.pk}))
@login_required
def configuration(request):
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	atentionhours=AtentionHours.objects.all()
	contactdetails=ContactDetail.objects.all()
	locationdetails=LocationDetail.objects.all()
	return render(request,'panel/configuration.html',locals())

@login_required 
def configuration_stats(request):
	title="Edicion de valores de iniciales"
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	if request.POST:
		form=ConfigurationForm(request.POST,request.FILES,instance=configuration)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:configuration'))
		else:
			message="Revise la informacion"
	else:
		form=ConfigurationForm(instance=configuration)
	return render(request,'panel/hooks/form.html',locals())
@login_required 
def configuration_rss(request):
	title="Edicion de Redes Sociales"
	configuration=Configuration.objects.all()
	if len(configuration) > 1 or len(configuration) <1:
		for c in configuration:
			c.delete()
		configuration=Configuration()
		configuration.save()
	else:
		configuration=configuration.first()
	if request.POST:
		form=ConfigurationRSSForm(request.POST,request.FILES,instance=configuration)
		if form.is_valid():
			form.save()
			return redirect(reverse('panel:configuration'))
		else:
			message="Revise la informacion"
	else:
		form=ConfigurationRSSForm(instance=configuration)
	return render(request,'panel/hooks/form.html',locals())

@login_required
def testimony_list(request):
	testimonies=Testimony.objects.all()
	return render(request,'panel/testimony/list.html',locals())
@login_required
def testimony_new(request):
	title='Crear Testimonio de la empresa'
	if request.POST:
		form=TestimonyForm(request.POST,request.FILES)
		if form.is_valid():
			testimony=form.save()
			if testimony.is_primary:
				ts=Testimony.objects.filter(is_primary=True)
				ts=ts.exclude(pk=testimony.pk)
				for t in ts:
					t.is_primary=False
					t.save()
			return redirect(reverse('panel:testimony_list'))
		else:
			message="Revisa la informacion"
	else:
		form=TestimonyForm()
	return render(request,'panel/hooks/form.html',locals())
@login_required
def testimony_edit(request,testimony_pk):
	testimony=Testimony.objects.get(pk=testimony_pk)
	title='Editar Testimonio de la empresa {0} '.format(testimony.pk)
	if request.POST:
		form=TestimonyForm(request.POST,request.FILES,instance=testimony)
		if form.is_valid():
			testimony=form.save()
			if testimony.is_primary:
				ts=Testimony.objects.filter(is_primary=True)

panel/templates/panel/configuration.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'panel/css/compiled/tables.css' %}"/>
    <link href="{% static 'panel/css/lib/jquery.dataTables.css' %}" type="text/css" rel="stylesheet"/>

    <!-- this page specific styles -->
    <link rel="stylesheet" href=" {% static 'panel/css/compiled/datatables.css' %}" type="text/css" media="screen"/>
    <style type="text/css">
     .other-info span{
        font-size: 20px;
        margin-bottom: 5%;
     }
     #main-stats{
        margin-left: 5%;
     }

    </style>
{% endblock%}
{% block content %}
 <!-- upper main stats -->
  <div id="pad-wrapper" class="users-list">
        
            <div class="row">
                <h2>CONFIGURACION PRINCIPAL</h2>
            </div>
        </div>
<div id="main-stats" class="users-list">
	<div class="row">
		
		<div class="pull-right" style="margin-top: 2%;margin-right: 5%;">
			<a href="{% url 'panel:configuration_stats'%}" class="btn-flat default icon-pencil
" style="width: 200px;text-align: center;font-size: 20px;"> Editar</a>
		</div>
	</div>
    <div class="row stats-row">
    	<h2>NUMEROS</h2>
        <div class="col-md-3 col-sm-3 stat">
            <div class="data">
            
                <span class="number">{{configuration.cases_success}}</span>
                Casos de Exito
            </div>
        </div>
        <div class="col-md-3 col-sm-3 stat">
            <div class="data">
                <span class="number">{{configuration.actual_clients}}</span>
                Clientes Actuales
            </div>
        </div>
        <div class="col-md-3 col-sm-3 stat">
            <div class="data">
                <span class="number">{{configuration.post_spain}}</span>
                Programas de Posgrado en España
            </div>
        </div>
        <div class="col-md-3 col-sm-3 stat last">
            <div class="data">
                <span class="number">{{configuration.aprovedd_tesis}} %</span>
                Tesis Aprobadas
            </div>
        </div>
    </div>
    <div class="row stats-row other-info">
        <h2>PRIMER SLIDER</h2>
        <span><b>Titulo de formulario: </b> {{ configuration.form_title }}</span><br>
        <span><b>Titulo Primer Slider: </b> {{ configuration.title_first }}</span><br>
        <span><b>Subtitulo Primer Slider: </b> {{ configuration.subtitle_first }}</span><br>
        <span><b>Multimedia del Primer Slider: </b> <a href="{{ configuration.first_slider.url }}">{{ configuration.first_slider }}</a></span><br>
        <h2>NOSOTROS</h2>
        <span><b>Mision</b><br>
            {{configuration.mision|linebreaks}}
        </span>
        <span><b>Vision</b><br>
            {{configuration.vision|linebreaks}}
        </span>
        <h2>OTRAS CONFIGURACIONES</h2>
        <span><b>Mostrar staff: </b> 
            {% if configuration.show_staff %}
                mostrar
            {% else %}
               no mostrar
            {% endif %}
        </span><br>
        <span><b>Contacto contenido</b><br>
            {{configuration.contact_content|linebreaks}}
        </span>
    </div>
</div>
<div id="pad-wrapper" class="atentionhours-list">
        
    <div class="table-wrapper products-table">
        <div class="row header">
            <h2>REDES SOCIALES</h2>
            <div class="col-md-12 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:configuration_rss'%}" class="btn-flat default pull-left">
                            
                            EDITAR
                        </a>
                    </div>
            <div class="col-md-12">
                <span><b>FACEBOOK: </b> <a href="{{ configuration.facebook }}">{{ configuration.facebook }}</a></span><br><br>
                <span><b>INSTAGRAM: </b> <a href="{{ configuration.instagram}}">{{ configuration.instagram }}</a></span><br><br>
                <span><b>LINKEDIN: </b> <a href="{{ configuration.linkedin}}">{{ configuration.linkedin }}</a></span><br><br>
                <span><b>YOUTUBE: </b> <a href="{{ configuration.youtube }}">{{ configuration.youtube }}</a></span><br><br>
                <span><b>TWITTER: </b> <a href="{{ configuration.twitter }}">{{ configuration.twitter }}</a></span><br><br>
                <span><b>EMAIL: </b> <a href="{{ configuration.mail }}">{{ configuration.mail }}</a></span><br>
            </div>
        </div>
    </div>
</div>


 <div id="pad-wrapper" class="atentionhours-list">
        
        <div class="table-wrapper products-table">
            <div class="row header">
                <h3>HORARIOS DE ATENCION</h3>
                    <div class="col-md-10 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:atention_new'%}" class="btn-flat success pull-right">
                            <span>&#43;</span>
                            Nuevo HORARIO
                        </a>
                    </div>
            </div>
            {% if message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <strong>Error!</strong> {{ message }} {{ response }}
                </div>
            {% endif %}
            <table id='example'>
                <thead>
                <tr>
                    <th>ID</th>
                    <th><span class="line"></span>DIAS</th>
                    <th><span class="line"></span>HORAS</th>
                    <th><span class="line"></span>Opciones</th>
                    <!--<th><span class="line"></span>Formato</th>-->
                </tr>
                </thead>
                <tbody>
                {% for s in atentionhours %}
                    <tr>
                        <td>{{s.id}}</td>
                        <td>{{s.title}}</td>
                        <td>
                            {{s.hours}}
                        </td>
                        <td>                    
                            <ul class="actions">
                                <li><a href="{% url 'panel:atention_edit' s.pk%}">Editar</a></li>
                                <li><a href="{% url 'panel:atention_delete' s.pk%}">Delete</a></li>
                               
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
               
                </tbody>
            </table>
        </div>
    </div>
    <div id="pad-wrapper" class="contactdetail-list">
        
        <div class="table-wrapper products-table">
            <div class="row header">
                <h3>DETALLES DE CONTACTO</h3>
                    <div class="col-md-10 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:contact_new'%}" class="btn-flat success pull-right">
                            <span>&#43;</span>
                            Nuevo DETALLE DE CONTACTO
                        </a>
                    </div>
            </div>
            {% if message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <strong>Error!</strong> {{ message }} {{ response }}
                </div>
            {% endif %}
            <table id='example2'>
                <thead>
                <tr>
                    <th>ID</th>
                    <th><span class="line"></span>TITULO</th>
                    <th><span class="line"></span>CONTENIDO</th>
                    <th><span class="line"></span>Opciones</th>
                    <!--<th><span class="line"></span>Formato</th>-->
                </tr>
                </thead>
                <tbody>
                {% for s in contactdetails %}
                    <tr>
                        <td>{{s.id}}</td>
                        <td>{{s.title}}</td>
                        <td>
                            {{s.content}}
                        </td>
                        <td>                    
                            <ul class="actions">
                                <li><a href="{% url 'panel:contact_edit' s.pk%}">Editar</a></li>
                                <li><a href="{% url 'panel:contact_delete' s.pk%}">Delete</a></li>
                               
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
               
                </tbody>
            </table>
        </div>
    </div>
    <div id="pad-wrapper" class="locationdetail-list">
        
        <div class="table-wrapper products-table">
            <div class="row header">
                <h3>DETALLES DE UBICACION</h3>
                    <div class="col-md-10 col-sm-12 col-xs-12 pull-right">
                        <a href="{% url 'panel:location_new'%}" class="btn-flat success pull-right">
                            <span>&#43;</span>
                            Nuevo DETALLE DE UBICACION
                        </a>
                    </div>
            </div>
            {% if message %}
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <strong>Error!</strong> {{ message }} {{ response }}
                </div>
            {% endif %}
            <table id='example3'>
                <thead>
                <tr>
                    <th>ID</th>
                    <th><span class="line"></span>TITULO</th>
                    <th><span class="line"></span>DIRECCION</th>
                    <th><span class="line"></span>Opciones</th>
                    <!--<th><span class="line"></span>Formato</th>-->
                </tr>
                </thead>
                <tbody>
                {% for s in locationdetails %}
                    <tr>
                        <td>{{s.id}}</td>
                        <td>{{s.title}}</td>
                        <td>
                            {{s.address}}
                        </td>
                        <td>                    
                            <ul class="actions">
                                <li><a href="{% url 'panel:location_edit' s.pk%}">Editar</a></li>
                                <li><a href="{% url 'panel:location_delete' s.pk%}">Delete</a></li>
                               
                            </ul>
                        </td>
                    </tr>
                {% endfor %}
               
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}
{% block scripts %}
<script src="{% static 'panel/js/jquery.dataTables.js' %}"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#example').dataTable({
                "sPaginationType": "full_numbers"
            });
            $('#example2').dataTable({
                "sPaginationType": "full_numbers"
            });
            $('#example3').dataTable({
                "sPaginationType": "full_numbers"
            });

        });
    </script>
{% endblock %}

panel/templates/panel/home.html
{% extends 'panel/nav.html' %}
{% load static %}
{% block content %}
hola mundo
{% endblock %}

panel/templates/panel/nav.html
{% extends 'panel/layout.html' %}
{% load static %}
{% block sidebar %}
<div id="sidebar-nav">
    <ul id="dashboard-menu">
		<li>
			<a href="{% url 'panel:team_list'%}">
			    <i class="icon-user"></i>
			    <span>Equipo</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:slider_list'%}">
			    <i class="icon-film"></i>
			    <span>Sliders</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:service_list'%}">
			    <i class="icon-group"></i>
			    <span>Servicios</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:pilar_list'%}">
			    <i class="icon-pushpin"></i>
			    <span>Pilares</span>
			</a>
		</li>
    	<li>
			<a href="{% url 'panel:option_list'%}">
			    <i class="icon-tasks"></i>
			    <span>Opcion para elegirno</span>
			</a>
		</li>
		<li>
			<a href="{% url 'panel:testimony_list'%}">
			    <i class="icon-quote-left"></i>
			    <span>Testimonios</span>
			</a>
		</li>
    	<li>
			<a href="{% url 'panel:post_list'%}">
			    <i class="icon-print"></i>
			    <span>Blog</span>
			</a>
		</li>
    	
	</ul>
</div>

{% endblock %}